### ISSUE TITLE
export data incorrect

### ISSUE THREAD

**Issue by scriptfans** [luckymarmot/Paw-PostmanDumpGenerator#1]
![3cda37a4-e463-415a-81e8-efb0e83b328c](https://cloud.githubusercontent.com/assets/359790/20253323/4e8da446-aa65-11e6-8032-07ede74b7c05.png)

When i export to postman dump v1, It's content type and data field seems to be wrong. I think it should be like this:
content-type: application/json
dataMode: 'json'
data: {
  "a": "1",
  "b": "abc"
}

Otherwise, When import into the postman, body will not be consistent.

**Comment by JonathanMontane** [comment]
@scriptfans thanks for the report! I'll look into it!

Would you mind including a screenshot of the header section too ? It could help me track down the issue. Thanks.

**Comment by scriptfans** [comment]
@JonathanMontane 

![edaecffd-a3e9-44e8-a4ff-d2aeb144396a](https://cloud.githubusercontent.com/assets/359790/20346425/e59be262-ac36-11e6-8e4d-e8f754c9b34c.png)

![bb319933-8908-4675-8a38-e3462cb7b0a4](https://cloud.githubusercontent.com/assets/359790/20346452/01a6993e-ac37-11e6-9a93-3f1ca10d7c75.png)

**Comment by JonathanMontane** [comment]
@scriptfans This should be fixed now. Can you try updating your extension to see if it works on your side?

You can find the extensions menu here:
![image](https://cloud.githubusercontent.com/assets/5136989/20347326/d0350baa-ac00-11e6-94e7-9846cd199879.png)

Click on the `check for updates` button in the center:
![image](https://cloud.githubusercontent.com/assets/5136989/20347349/ed492ca8-ac00-11e6-8e39-ec6eed026a88.png)

**Comment by scriptfans** [comment]
It's work! thanks :)
